sudo: required
dist: trusty
language: node_js
node_js:
- 10.15.1
branches:
  only:
  - master
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm i -g @angular/cli karma
- npm i
- ng test --watch=false
- ng lint
script:
- ng build --prod
after_success:
notifications:
  email:
    on_failure: always
    on_success: change
